"""
Postprocessing commands for ensemble WRF output
"""

import re
import sys
from pathlib import Path
from typing import Optional

import click
import xarray as xr

from wrf_ensembly import experiment, processors
from wrf_ensembly.click_utils import GroupWithStartEndPrint, pass_experiment_path
from wrf_ensembly.console import logger
from wrf_ensembly.postprocess.compression import (
    CompressionConfigError,
    validate_compression_config,
)
from wrf_ensembly.postprocess.streaming_pipeline import (
    process_cycle_single_member,
    process_cycle_streaming,
)


@click.group(name="postprocess", cls=GroupWithStartEndPrint)
def postprocess_cli():
    """Postprocessing commands for ensemble output."""
    pass


@postprocess_cli.command()
@pass_experiment_path
def print_variables_to_keep(experiment_path: Path):
    """
    Prints which variables will be kept in the wrfout files after postprocessing.

    This is useful to check if the variables you want to keep are actually kept
    or to check how the regex filters are applied.

    The variables are defined in the `PostprocessConfig:variables_to_keep` variable
    of the configuration file.

    Cycle 0 output for member 0 must exist for this command to work.
    """

    logger.setup("postprocess-print_variables_to_keep", experiment_path)
    exp = experiment.Experiment(experiment_path)

    if not exp.cfg.postprocess.variables_to_keep:
        logger.warning("`variables_to_keep` is not set in the config, exiting")
        sys.exit(0)

    # Find a sample forecast file, cycle 0, member 0
    scratch_forecast_dir = exp.paths.scratch_forecasts_path(0)
    forecast_files = list(scratch_forecast_dir.rglob("member_00/wrfout*"))
    if len(forecast_files) == 0:
        logger.error("No forecast files found, exiting")
        sys.exit(1)

    # Use the first file
    forecast_file = forecast_files[0]
    logger.info(f"Using {forecast_file} as sample file")
    ds = xr.open_dataset(forecast_file, decode_times=False)

    # Add variables that would normally be generated by xwrf_post
    for new_var in [
        "air_potential_temperature",
        "air_pressure",
        "wind_east",
        "wind_north",
        "air_density",
    ]:
        ds[new_var] = xr.zeros_like(ds["THM"])
    ds = ds.rename({"XTIME": "t"})

    filters = [re.compile(x) for x in exp.cfg.postprocess.variables_to_keep]
    logger.info("Variables in output file:")
    for var in ds.data_vars:
        for f in filters:
            if f.match(str(var)):
                logger.info(f"{f} -> {var}: ({ds[var].dims}) ({ds[var].dtype})")
                break


@postprocess_cli.command()
@click.option(
    "--cycle",
    type=int,
    help="Cycle to process. Defaults to current cycle.",
)
@click.option(
    "--only-last-timestep",
    is_flag=True,
    default=False,
    help="Only process the last timestep of the cycle.",
)
@pass_experiment_path
def run(
    experiment_path: Path,
    cycle: Optional[int],
    only_last_timestep: bool,
):
    """
    Run the complete postprocessing pipeline for a single cycle.

    Processes all ensemble members through the configured processor pipeline and writes
    the final output files directly, without intermediate files. Which files are produced
    depends on the `compute_ensemble_mean`, `compute_ensemble_sd` and `keep_per_member`
    options of the `[postprocess]` config section; statistics that are turned off are
    never computed.

    This command processes ONE cycle at a time with no side effects, making it
    safe to run multiple instances in parallel for different cycles:

    \b
        # Using GNU parallel
        parallel -j 4 wrf_ensembly postprocess run --cycle {} ::: {0..23}

    \b
        # Using SLURM array jobs
        #SBATCH --array=0-23
        wrf_ensembly postprocess run --cycle $SLURM_ARRAY_TASK_ID
    """

    logger.setup("postprocess-run", experiment_path)
    exp = experiment.Experiment(experiment_path)

    if cycle is None:
        cycle = exp.current_cycle_i

    logger.info(f"Processing cycle {cycle}: {exp.cycles[cycle]}")

    # Validate compression configuration
    try:
        validate_compression_config(exp.cfg.postprocess)
        logger.info(
            f"Compression: {exp.cfg.postprocess.compression} "
            f"(level={exp.cfg.postprocess.compression_level}, shuffle={exp.cfg.postprocess.shuffle})"
        )
        if exp.cfg.postprocess.significant_digits is not None:
            logger.info(
                f"Quantization: {exp.cfg.postprocess.quantize_mode} "
                f"(default digits={exp.cfg.postprocess.significant_digits})"
            )
    except CompressionConfigError as e:
        logger.error(f"Compression configuration error: {e}")
        sys.exit(1)

    # Bail out before touching any wrfout file if nothing would be written
    pp = exp.cfg.postprocess
    if not (pp.compute_ensemble_mean or pp.compute_ensemble_sd or pp.keep_per_member):
        logger.error(
            "Postprocessing would produce no output: compute_ensemble_mean, "
            "compute_ensemble_sd and keep_per_member are all false. Enable at least "
            "one of them in the [postprocess] section of the config."
        )
        sys.exit(1)

    # Create processor pipeline
    try:
        pipeline = processors.create_pipeline_from_config(
            exp.cfg.postprocess.processors
        )
        logger.info(
            f"Created pipeline with processors: {[p.name for p in pipeline.processors]}"
        )
    except Exception as e:
        logger.error(f"Failed to create processor pipeline: {e}")
        sys.exit(1)

    n_members = exp.cfg.assimilation.n_members
    logger.info(f"Ensemble size: {n_members} members")

    # Choose processing function based on ensemble size
    if n_members == 1:
        logger.info("Single member ensemble - skipping statistics computation")
        # The single-member path can only ever write the "mean" file, which holds the
        # member's own data, so a disabled mean leaves it with nothing to do.
        if not pp.compute_ensemble_mean:
            logger.error(
                "compute_ensemble_mean is false but the ensemble has a single member, "
                "so no output can be produced."
            )
            sys.exit(1)
        process_func = process_cycle_single_member
    else:
        logger.info(
            f"Outputs: mean={pp.compute_ensemble_mean}, sd={pp.compute_ensemble_sd}, "
            f"per-member={pp.keep_per_member}"
        )
        process_func = process_cycle_streaming

    def log_result(source: str, result) -> None:
        """Report which output files a source produced, if any."""

        if result is None:
            logger.warning(f"No {source} files found to process")
            return

        paths = result if isinstance(result, tuple) else (result,)
        names = ", ".join(p.name for p in paths if p is not None)
        logger.info(f"{source.capitalize()} output: {names}")

    # Process forecast files
    logger.info("Processing forecast files...")
    log_result(
        "forecast",
        process_func(
            exp,
            cycle,
            pipeline,
            source="forecast",
            only_last_timestep=only_last_timestep,
        ),
    )

    # Process analysis files
    logger.info("Processing analysis files...")
    log_result(
        "analysis",
        process_func(
            exp,
            cycle,
            pipeline,
            source="analysis",
            only_last_timestep=only_last_timestep,
        ),
    )

    logger.info(f"Cycle {cycle} postprocessing complete")


@postprocess_cli.command()
@click.option(
    "--cycle",
    type=int,
    help="Cycle to clean up. Defaults to current cycle.",
)
@click.option(
    "--remove-wrfout/--keep-wrfout",
    default=True,
    help="Remove the raw wrfout files (default: remove).",
)
@pass_experiment_path
def clean(experiment_path: Path, cycle: Optional[int], remove_wrfout: bool):
    """
    Clean up the scratch directory for the given cycle.

    Use after running the postprocessing pipeline to save disk space.
    By default, removes raw wrfout files. Use --keep-wrfout to preserve them.
    """

    logger.setup("postprocess-clean", experiment_path)
    exp = experiment.Experiment(experiment_path)

    if cycle is None:
        cycle = exp.current_cycle_i

    logger.info(f"Cleaning scratch for cycle {cycle}")

    scratch_dirs = [
        exp.paths.scratch_forecasts_path(cycle),
        exp.paths.scratch_analysis_path(cycle),
    ]

    for scratch_dir in scratch_dirs:
        if not scratch_dir.exists():
            continue

        if remove_wrfout:
            for f in scratch_dir.rglob("wrfout*"):
                logger.info(f"Removing {f}")
                f.unlink()
