[metadata]
name = "test"
description = """\
This is a test experiment to test dart_wrf.
"""

[environment]
PREFIX = "/mnt/scratch-1/wrf-dart-intro"
WRF_DIR = "/mnt/scratch-1/wrf-dart-intro/WRF"
WRFIO_NCD_LARGE_FILE_SUPPORT = "1"
WRF_CHEM = "1"
EM_CORE = "1"

[directories]
wrf_root = "/mnt/scratch-1/wrf-dart-intro/WRF"
wps_root = "/mnt/scratch-1/wrf-dart-intro/WPS"
dart_root = "/mnt/scratch-1/wrf-dart-intro/DART"


[domain_control]
xy_resolution = [26, 26] # km
xy_size = [70, 70]       # grid points

projection = "lambert"
ref_lat = 26.0
ref_lon = -30.0
truelat1 = 33.0
truelat2 = 33.0
stand_lon = -22.0

[time_control]
# Start-end times for the whole experiment (all assimilation cycles)
start = 2021-09-01T00:00:00Z
end = 2021-09-03T00:00:00Z
# Corresponds to interval_seconds in WRF, but in minutes
boundary_update_interval = 360 # 6h
# Output file interval, in minutes (WRF history_interval)
output_interval = 60
# How often the analysis is run, in minutes
analysis_interval = 1440 # 24h


[data]
wps_geog = "/mnt/scratch-1/wrf-dart-intro/data/WPS_GEOG"
meteorology = "/mnt/scratch-1/wrf-dart-intro/data/ERA5_CDS_September_2021"
meteorology_vtable = "Vtable.ERA-interim.pl"

[assimilation]
n_members = 4

# -- WRF NAMELIST OPTIONS --
[wrf_namelist]

[wrf_namelist.time_control]
input_from_file = true
history_interval = 60
frames_per_outfile = 1
restart = false
restart_interval = 2881
io_form_history = 2
io_form_restart = 102
io_form_input = 2
io_form_boundary = 2
io_form_auxhist2 = 2
debug_level = 0
diag_print = 0

[wrf_namelist.domains]
eta_levels = [
  1.0000,
  0.9980,
  0.9940,
  0.9870,
  0.9750,
  0.9590,
  0.9390,
  0.9160,
  0.8920,
  0.8650,
  0.8350,
  0.8020,
  0.7660,
  0.7270,
  0.6850,
  0.6400,
  0.5920,
  0.5420,
  0.4970,
  0.4565,
  0.4205,
  0.3877,
  0.3582,
  0.3317,
  0.3078,
  0.2863,
  0.2670,
  0.2496,
  0.2329,
  0.2188,
  0.2047,
  0.1906,
  0.1765,
  0.1624,
  0.1483,
  0.1342,
  0.1201,
  0.1060,
  0.0919,
  0.0778,
  0.0657,
  0.0568,
  0.0486,
  0.0409,
  0.0337,
  0.0271,
  0.0209,
  0.0151,
  0.0097,
  0.0047,
  0.0000,
]
time_step = 60
time_step_fract_num = 0
time_step_fract_den = 1
e_vert = 51
num_metgrid_levels = 38
num_metgrid_soil_levels = 4
grid_id = 1
parent_id = 0
i_parent_start = 1
j_parent_start = 1
parent_grid_ratio = 1
parent_time_step_ratio = 1
feedback = 0
smooth_option = 1
p_top_requested = 1500
lagrange_order = 2
interp_type = 2
interp_theta = false
hypsometric_opt = 2
extrap_type = 2
t_extrap_type = 2
use_surface = true
use_levels_below_ground = true
lowest_lev_from_sfc = false
force_sfc_in_vinterp = 1
zap_close_levels = 500


[wrf_namelist.physics]
mp_physics = 8
ra_lw_physics = 4
ra_sw_physics = 4
radt = 10
sf_sfclay_physics = 2
sf_surface_physics = 2
bl_pbl_physics = 2
bldt = 0
cu_physics = 6
cudt = 5
mp_zero_out = 2
mp_zero_out_thresh = 1e-10
isfflx = 1
ifsnow = 0
icloud = 1
surface_input_source = 1
num_soil_layers = 4
o3input = 2
aer_opt = 1
sst_skin = 1


[wrf_namelist.dynamics]
zdamp = [5000, 5000, 5000]
non_hydrostatic = [true, true]
w_damping = 1
diff_opt = 1
km_opt = 4
damp_opt = 3
dampcoef = [0.2, 0.01, 0.2]
moist_adv_opt = [2, 2]
scalar_adv_opt = [2, 2]
diff_6th_opt = [2, 2]
diff_6th_factor = [0.25, 0.12]
epssm = 0.1

[wrf_namelist.bdy_control]
specified = [true, false]
nested = [false, true]

[wrf_namelist.namelist_quilt]
spec_bdy_width = 5
spec_zone = 1
relax_zone = 4
nio_tasks_per_group = 2
nio_groups = 1

[wrf_namelist.wrfvar1]
check_max_iv_print = false
write_increments = false

[wrf_namelist.wrfvar2]

[wrf_namelist.wrfvar3]

[wrf_namelist.wrfvar4]
use_synopobs = false
use_shipsobs = false
use_metarobs = false
use_soundobs = false
use_pilotobs = false
use_airepobs = false
use_geoamvobs = false
use_polaramvobs = false
use_bogusobs = false
use_buoyobs = false
use_profilerobs = false
use_satemobs = false
use_gpspwobs = false
use_gpsrefobs = false
use_qscatobs = false
use_radarobs = false
use_radar_rv = false
use_radar_rf = false
use_airsretobs = false

[wrf_namelist.wrfvar5]
check_max_iv = false
put_rand_seed = true

[wrf_namelist.wrfvar6]
max_ext_its = 1
ntmax = 200
eps = 0.01

[wrf_namelist.wrfvar7]
cv_options = 3
# Set by the [pertubation_bank] group
#as1 = [PERT_SCALING, 2.0, 1.5]
#as2 = [PERT_SCALING, 2.0, 1.5]
#as3 = [PERT_SCALING, 2.0, 1.5]
#as4 = [PERT_SCALING, 2.0, 1.5]
#as5 = [PERT_SCALING, 2.0, 1.5]
rf_passes = 6
var_scaling1 = 1.0
var_scaling2 = 1.0
var_scaling3 = 1.0
var_scaling4 = 1.0
var_scaling5 = 1.0
len_scaling1 = 1.0
len_scaling2 = 1.0
len_scaling3 = 1.0
len_scaling4 = 1.0
len_scaling5 = 1.0
je_factor = 1.0

[wrf_namelist.wrfvar8]

[wrf_namelist.wrfvar9]
trace_use = false
trace_memory = false
trace_all_pes = false
trace_csv = false
use_html = false

[wrf_namelist.wrfvar10]

[wrf_namelist.wrfvar11]
cv_options_hum = 1
check_rh = 1
set_omb_rand_fac = 1.0
seed_array1 = 1
seed_array2 = 1

[wrf_namelist.wrfvar12]

[wrf_namelist.wrfvar13]
vert_corr = 2
vertical_ip = 0
vert_evalue = 1
max_vert_var1 = 99.0
max_vert_var2 = 99.0
max_vert_var3 = 99.0
max_vert_var4 = 99.0
max_vert_var5 = 0.0

[wrf_namelist.wrfvar14]

[wrf_namelist.wrfvar15]
num_pseudo = 0

[wrf_namelist.wrfvar16]

[wrf_namelist.wrfvar17]
analysis_type = 'RANDOMCV'

[wrf_namelist.wrfvar18]
analysis_date = 'yyyy-mm-dd_hh:mm:ss.0000'

[wrf_namelist.wrfvar19]
[wrf_namelist.wrfvar20]
[wrf_namelist.wrfvar21]
[wrf_namelist.wrfvar22]
[wrf_namelist.wrfvar23]
