[metadata]
name = "aeolus_fmeeting_control"
description = """\
Control run, 16 members, 1 day (4 cycles)
For Aeolus final meeting presentation 2023-09-20

Experiment domain: North Africa, Atlantic Ocean, 2021-09-01 to 2021-09-02
"""

[environment]
PREFIX = "/mnt/scratch-1/wrf-dart-intro"
WRF_DIR = "/mnt/scratch-1/wrf-dart-intro/WRF"
WRFIO_NCD_LARGE_FILE_SUPPORT = "1"
WRF_CHEM = "1"
EM_CORE = "1"

[directories]
wrf_root = "/mnt/scratch-1/wrf-dart-intro/WRF"
wps_root = "/mnt/scratch-1/wrf-dart-intro/WPS"
dart_root = "/mnt/scratch-1/wrf-dart-intro/DART"
wrfda_root = "/mnt/scratch-1/wrf-dart-intro/WRFDA"

[domain_control]
xy_resolution = [26, 26] # km
xy_size = [500, 250]     # grid points

projection = "lambert"
ref_lat = 20
ref_lon = -27.0
truelat1 = 0.0
truelat2 = 35.0
stand_lon = -27.0

[time_control]
# Start-end times for the whole experiment (all assimilation cycles)
start = 2021-09-01T00:00:00Z
end = 2021-09-02T00:00:00Z
# Corresponds to interval_seconds in WRF, but in minutes
boundary_update_interval = 360 # 6h
# Output file interval, in minutes (WRF history_interval)
output_interval = 180
# How often the analysis is run, in minutes
analysis_interval = 360 # 6h


[data]
wps_geog = "/mnt/scratch-1/wrf-dart-intro/data/WPS_GEOG"
meteorology = "/mnt/scratch-1/wrf-dart-intro/data/GFS_ANL_September_2021/20210901"
meteorology_vtable = "Vtable.GFS"


[pertubations.V]
mean = 0
sd = 10
rounds = 5

[pertubations.U]
mean = 0
sd = 10
rounds = 5

[assimilation]
n_members = 16
# Which variables to carry forward from the previous cycle
cycled_variables = [
  'U',
  'V',
  'P',
  'PH',
  'T',
  'MU',
  'QVAPOR',
  'QCLOUD',
  'QRAIN',
  'QICE',
  'QSNOW',
  'QGRAUP',
  'QNICE',
  'QNRAIN',
  'U10',
  'V10',
  'T2',
  'Q2',
  'PSFC',
  'TSLB',
  'SMOIS',
  'TSK',
]
# Which variables to use in the state vector
# Should probably match the DART namelist!
state_variables = ['U', 'V', 'W', 'PH', 'T', 'MU', 'QVAPOR', 'PSFC']

[slurm]
partition = "cascadelake"
nodes = 1
ntasks-per-node = 10
mail-user = "ageorgiou@noa.gr"
mail-type = "END,FAIL"
mem = "45GB"
cpus-per-task = 1
env_modules = [
  "compiler/2023.2.0",
  "openmpi/4.1.5-intel",
  "hdf5/1.14.1-intel",
  "netCDF/4.9.2-intel",
]

# -- WRF NAMELIST OPTIONS --
[wrf_namelist]

[wrf_namelist.time_control]
input_from_file = true
history_interval = 60
frames_per_outfile = 1
restart = false
restart_interval = 3600
io_form_history = 2
io_form_restart = 2
io_form_input = 2
io_form_boundary = 2
io_form_auxhist2 = 2
debug_level = 0
diag_print = 0

[wrf_namelist.domains]
time_step = 120             # 6*dx in km https://esrl.noaa.gov/gsd/wrfportal/namelist_input_options.html
time_step_fract_num = 0
time_step_fract_den = 1
max_dom = 1
e_vert = 45
num_metgrid_levels = 34
num_metgrid_soil_levels = 4
grid_id = 1
parent_id = 0
i_parent_start = 1
j_parent_start = 1
parent_grid_ratio = 1
parent_time_step_ratio = 1
feedback = 1
smooth_option = 0
p_top_requested = 5000
smooth_cg_topo = true
dzstretch_s = 1.1


[wrf_namelist.physics]
sst_update = 0
mp_physics = 10
progn = 1
do_radar_ref = 1
ra_lw_physics = 4
ra_sw_physics = 4
radt = 20
sf_sfclay_physics = 2
sf_surface_physics = 2
bl_pbl_physics = 2
bldt = 0
cu_physics = 5
cu_diag = 1
cudt = 0
ishallow = 0
isfflx = 1
ifsnow = 1
icloud = 1
surface_input_source = 1
num_soil_layers = 4
sf_urban_physics = 0
mp_zero_out = 2
mp_zero_out_thresh = 1e-12
maxiens = 1
maxens = 3
maxens2 = 3
maxens3 = 16
ensdim = 144
cu_rad_feedback = true


[wrf_namelist.dynamics]
hybrid_opt = 2
w_damping = 0
diff_opt = 2
km_opt = 4
diff_6th_opt = 0
diff_6th_factor = 0.12
base_temp = 290
damp_opt = 3
zdamp = 5000
dampcoef = 0.2
khdif = 0
kvdif = 0
non_hydrostatic = true
moist_adv_opt = 1
scalar_adv_opt = 1
gwd_opt = 1

[wrf_namelist.namelist_quilt]
nio_tasks_per_group = 0
nio_groups = 1

[wrf_namelist.bdy_control]
spec_bdy_width = 5
specified = true
