[tool.poetry]
name = "wrf-ensembly"
version = "0.1.0"
description = "Support scripts for using DART w/ WRF"
authors = ["Thanasis Georgiou <ageorgiou@noa.gr>"]
readme = "README.md"
packages = [{ include = "wrf_ensembly" }]

[tool.poetry.dependencies]
python = "^3.10"
typer = "^0.7.0"
netcdf4 = "^1.6.2"
tomli = "^2.0.1"
pydantic = "^1.10.6"
rich = "^13.3.5"
jinja2 = "^3.1.2"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
