import json
from pathlib import Path
from typing import Tuple

import numpy as np
import xarray as xr
from scipy.ndimage import gaussian_filter

from wrf_ensembly import config
from wrf_ensembly.console import logger


def set_boundaries(arr: np.ndarray, boundary_size: int, value: float) -> np.ndarray:
    """Sets the boundaries of an array to a given value."""

    slices = [slice(None)] * arr.ndim
    for dim in range(arr.ndim):
        if arr.shape[dim] < 2 * boundary_size:
            continue

        slices[dim] = slice(None, boundary_size)
        arr[tuple(slices)] = value
        slices[dim] = slice(-boundary_size, None)
        arr[tuple(slices)] = value
        slices[dim] = slice(None)  # Reset slice for next dimension
    return arr


def generate_perturbation_field(
    shape: Tuple[int, ...],
    mean: float,
    sd: float,
    sigma=2.5,
    boundary=0,
    min_value: float | None = None,
    max_value: float | None = None,
):
    """
    Generates a random pseudo-spatially-collerated field. Based on the technique
    described in Tsikerdekis et. al. 2021 (https://doi.org/10.5194/acp-21-2637-2021).

    The field is generated by creating an array of random numbers (sampled from N(1, 10))
    and applying consequent rounds of gaussian smoothing. The field is then normalized
    to have a mean of `mean` and a standard deviation of `sd`.

    Args:
        shape: The shape of the random field to create
        mean: Desired mean value of the field, after normalization
        sd: Desired standard deviation of the field, after normalization
        sigma: Standard deviation for the Gaussian filter
        min_value: Optional minimum value for the field. If provided, values below this will be set to this value.
        max_value: Optional maximum value for the field. If provided, values above this will be set to this value.

    Returns:
        The generated field as a numpy array.
    """
    x = np.random.normal(1, 10, shape)

    if boundary > 0:
        x = set_boundaries(x, boundary, 1)

    x = gaussian_filter(x, sigma=sigma)
    x = (x - x.mean()) / x.std()
    x = x * sd + mean

    if min_value is not None:
        x = np.maximum(x, min_value)
    if max_value is not None:
        x = np.minimum(x, max_value)
    return x


def generate_perturbation_ensemble(
    n_members: int,
    shape: Tuple[int, ...],
    mean: float,
    sd: float,
    sigma=2.5,
    boundary=0,
    min_value: float | None = None,
    max_value: float | None = None,
) -> np.ndarray:
    """
    Generates perturbation fields for all ensemble members at once.

    Same algorithm as `generate_perturbation_field`, but generates all members in a
    single batch and applies Gaussian smoothing only on the spatial axes (not the
    member axis), which is significantly faster than calling `generate_perturbation_field`
    in a loop.

    Args:
        n_members: Number of ensemble members
        shape: The shape of a single member's field (e.g., (time, z, y, x))
        mean: Desired mean value of each member's field, after normalization
        sd: Desired standard deviation of each member's field, after normalization
        sigma: Standard deviation for the Gaussian filter
        boundary: Size of boundary to set to neutral value
        min_value: Optional minimum value clamp
        max_value: Optional maximum value clamp

    Returns:
        Array of shape (n_members, *shape) with perturbation fields.
    """
    batch_shape = (n_members, *shape)
    x = np.random.normal(1, 10, batch_shape)

    if boundary > 0:
        for i in range(n_members):
            x[i] = set_boundaries(x[i], boundary, 1)

    # Apply Gaussian filter only on spatial axes (all axes except the first/member axis)
    spatial_axes = tuple(range(1, len(batch_shape)))
    x = gaussian_filter(x, sigma=sigma, axes=spatial_axes)

    # Normalize per member
    for i in range(n_members):
        x[i] = (x[i] - x[i].mean()) / x[i].std()
        x[i] = x[i] * sd + mean

    if min_value is not None:
        np.maximum(x, min_value, out=x)
    if max_value is not None:
        np.minimum(x, max_value, out=x)

    return x


def edge_taper(ny: int, nx: int, border_width: int):
    """
    Tapers the center of a 2D array to zero, leaving a border of specified width unchanged.
    The transition from the border to the center is smooth, following a linear decay of length
    equal to the border width.

    So a perturbation field with `edge_taper(10)` will have a 10-pixel wide border
    that is non-zero.

    Args:
        ny: Number of rows in the array
        nx: Number of columns in the array
        border_width: Width of the border to remain unchanged
    Returns:
        The tapered array mask as a numpy array.
    """

    # Compute distance of each point from the nearest edge
    y_indices = np.arange(ny)
    x_indices = np.arange(nx)
    dist_left = x_indices
    dist_right = nx - 1 - x_indices
    dist_top = y_indices
    dist_bottom = ny - 1 - y_indices

    dist_x = np.minimum(dist_left, dist_right)
    dist_y = np.minimum(dist_top, dist_bottom)
    xx, yy = np.meshgrid(dist_x, dist_y)
    dist = np.minimum(xx, yy)

    taper = 1.0 - np.clip(dist / border_width, 0, 1)

    return taper


def reapplied_parameters(cfg: config.Config) -> list[str]:
    """
    The `kind = "parameter"` variables that must be perturbed again at every cycle after
    the first. That is only in `wrfinput` cycling mode, where each cycle starts from a
    fresh wrfinput, and only if they are not in `cycled_variables` (then the perturbed
    value is carried over). In `restart` mode, the restart file carries them over.
    """

    if cfg.assimilation.cycling_mode != "wrfinput":
        return []
    return [
        name
        for name, var in cfg.perturbations.variables.items()
        if var.kind == "parameter" and name not in cfg.assimilation.cycled_variables
    ]


def applied_at_cycle(cfg: config.Config, cycle_i: int) -> list[str]:
    """
    The variables perturbed at the start of a cycle: all of them at the first cycle, and
    later the `perturb_every_cycle` state variables and `reapplied_parameters`.
    """

    if cycle_i == 0:
        return list(cfg.perturbations.variables)
    every_cycle = [
        name
        for name, var in cfg.perturbations.variables.items()
        if var.kind == "state" and var.perturb_every_cycle
    ]
    return every_cycle + reapplied_parameters(cfg)


def generate_perturbations_for_cycle(
    cycle_i: int,
    perturbations_cfg: config.PerturbationsConfig,
    reapplied_parameters: list[str],
    n_members: int,
    experiment_name: str,
    ic_path: Path,
    diag_dir: Path,
):
    """
    Generates perturbations for a given cycle and stores them in the diag directory.
    This is a module-level function taking plain arguments so that it can be pickled and
    dispatched to a worker process (see `Experiment.generate_perturbations_for_cycles`).

    After the first cycle, `perturb_every_cycle` state variables get a new field and
    `reapplied_parameters` (see the function of that name) reuse the first cycle's. If
    only the latter are needed, a symlink to cycle 0's file is created instead. If neither
    is, no file is written and `apply-perturbations` is skipped for that cycle.
    The midcycle taper is applied at perturbation application time rather than here.
    """

    if len(perturbations_cfg.variables) == 0:
        logger.warning("No perturbations defined in config, skipping")
        return

    if perturbations_cfg.seed is not None:
        # Every cycle needs its own fields. The first cycle keeps the plain seed, so its
        # ensemble is the same as before later cycles got their own seeds.
        seed = perturbations_cfg.seed
        if cycle_i > 0:
            seed = [perturbations_cfg.seed, cycle_i]
        logger.warning(f"Setting random seed to {seed}")
        np.random.seed(seed)

    pert_dir = diag_dir / "perturbations"
    pert_dir.mkdir(parents=True, exist_ok=True)
    pert_file = pert_dir / f"perts_cycle_{cycle_i}.nc"
    pert_file.unlink(missing_ok=True)

    if cycle_i == 0:
        new_variables = list(perturbations_cfg.variables)
        reused_variables = []
    else:
        new_variables = [
            name
            for name, var in perturbations_cfg.variables.items()
            if var.kind == "state" and var.perturb_every_cycle
        ]
        reused_variables = reapplied_parameters

    if not new_variables and not reused_variables:
        logger.info(f"Nothing to perturb at cycle {cycle_i}")
        return

    first_cycle_pert_file = pert_dir / "perts_cycle_0.nc"
    if reused_variables and not first_cycle_pert_file.exists():
        raise FileNotFoundError(
            f"Perturbation file for first cycle not found at {first_cycle_pert_file}"
        )
    if not new_variables:
        # Everything comes from cycle 0, symlink instead of copying
        pert_file.symlink_to(first_cycle_pert_file.name)
        logger.info(
            f"Symlinked perturbations for cycle {cycle_i} to cycle 0 (same fields)"
        )
        return

    # Open the first wrfinput file to get the shape of each variable
    wrfinput = xr.open_dataset(ic_path)

    # Generate the perturbation fields
    perts = xr.Dataset()
    for var in new_variables:
        pert_config = perturbations_cfg.variables[var]
        logger.debug(f"\tVariable: {var}, config: {pert_config}")
        arr = generate_perturbation_ensemble(
            n_members=n_members,
            shape=wrfinput[var].shape,
            mean=pert_config.mean,
            sd=pert_config.sd,
            sigma=pert_config.gaussian_sigma,
            boundary=pert_config.boundary,
            min_value=pert_config.min_value,
            max_value=pert_config.max_value,
        )
        perts[var] = xr.DataArray(
            arr,
            dims=("member", *wrfinput[var].dims),
            coords={"member": range(n_members)},
            attrs={"cfg": json.dumps(pert_config.__dict__)},
        )

    if reused_variables:
        first_cycle_perts = xr.open_dataset(first_cycle_pert_file)
        for var in reused_variables:
            logger.info(f"Reusing perturbation field from first cycle for {var}")
            if var not in first_cycle_perts:
                raise ValueError(
                    f"Variable {var} not found in perturbation file for first cycle"
                )
            perts[var] = first_cycle_perts[var]
            perts[var].attrs = first_cycle_perts[var].attrs

    # Write the dataset to a netCDF file
    encoding = {
        var: {
            "zlib": True,
            "complevel": 5,
            "dtype": "float32",
            "least_significant_digit": 3,
        }
        for var in perts.data_vars
    }
    # Set chunksize for all variables: 1 on member and time, full size on rest
    for var in perts.data_vars:
        chunks = [1, 1] + [s for s in perts[var].shape[2:]]
        encoding[var]["chunksizes"] = chunks
    perts.attrs["experiment_name"] = experiment_name
    perts.attrs["cycle"] = cycle_i

    logger.info(f"Writing perturbations for {cycle_i} to {pert_file}")
    perts.to_netcdf(pert_file, encoding=encoding)

    wrfinput.close()
